export const BLOG_ADD_REQUEST = 'BLOG_ADD_REQUEST'
export const BLOG_ADD_SUCCESS = 'BLOG_ADD_SUCCESS'
export const BLOG_ADD_FAIL = 'BLOG_ADD_FAIL'
export const BLOG_ADD_RESET = 'BLOG_ADD_RESET'

export const BLOG_GET_REQUEST = 'BLOG_GET_REQUEST'
export const BLOG_GET_SUCCESS = 'BLOG_GET_SUCCESS'
export const BLOG_GET_FAIL = 'BLOG_GET_FAIL'

export const BLOG_UPDATE_REQUEST = 'BLOG_UPDATE_REQUEST'
export const BLOG_UPDATE_SUCCESS = 'BLOG_UPDATE_SUCCESS'
export const BLOG_UPDATE_FAIL = 'BLOG_UPDATE_FAIL'
export const BLOG_UPDATE_RESET = 'BLOG_UPDATE_RESET'

export const BLOG_DELETE_REQUEST = 'BLOG_DELETE_REQUEST'
export const BLOG_DELETE_SUCCESS = 'BLOG_DELETE_SUCCESS'
export const BLOG_DELETE_FAIL = 'BLOG_DELETE_FAIL'


export const BLOG_DETAILS_REQUEST = 'BLOG_DETAILS_REQUEST'
export const BLOG_DETAILS_SUCCESS = 'BLOG_DETAILS_SUCCESS'
export const BLOG_DETAILS_FAIL = 'BLOG_DETAILS_FAIL'

export const BLOG_REMOVE = 'BLOG_REMOVE'
export const BLOG_EDIT = 'BLOG_EDIT'
export const BLOG_SAVE_SHIPPING_ADDRESS = 'BLOG_SAVE_SHIPPING_ADDRESS'
export const BLOG_SAVE_PAYMENT_METHOD = 'BLOG_SAVE_PAYMENT_METHOD'
