export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST'
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS'
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL'

export const CART_GET_ITEM_REQUEST = 'CART_GET_ITEM_REQUEST'
export const CART_GET_ITEM_SUCCESS = 'CART_GET_ITEM_SUCCESS'
export const CART_GET_ITEM_FAIL = 'CART_GET_ITEM_FAIL'

export const CART_DELETE_ITEM_REQUEST = 'CART_DELETE_ITEM_REQUEST'
export const CART_DELETE_ITEM_SUCCESS = 'CART_DELETE_ITEM_SUCCESS'
export const CART_DELETE_ITEM_FAIL = 'CART_DELETE_ITEM_FAIL'



export const CART_CLEAR_ITEMS_REQUEST = 'CART_RESET_REQUEST'
export const CART_CLEAR_ITEMS_SUCCESS = 'CART_RESET_SUCCESS'
export const CART_CLEAR_ITEMS_FAIL = 'CART_RESET_FAIL'

export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_EDIT_ITEM = 'CART_EDIT_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'


export const CART_ITEMS_SELECT = 'CART_ITEMS_SELECT'
export const CART_ITEMS_DESELECT = 'CART_ITEMS_DESELECT'

export const CART_SAVE_GIFT_MESSAGE = "CART_SAVE_GIFT_MESSAGE"