export const COUPON_ADD_REQUEST = "COUPON_ADD_REQUEST";
export const COUPON_ADD_SUCCESS = "COUPON_ADD_SUCCESS";
export const COUPON_ADD_FAIL = "COUPON_ADD_FAIL";
export const COUPON_ADD_RESET = "COUPON_ADD_RESET";

export const COUPON_GET_REQUEST = "COUPON_GET_REQUEST";
export const COUPON_GET_SUCCESS = "COUPON_GET_SUCCESS";
export const COUPON_GET_FAIL = "COUPON_GET_FAIL";

export const COUPON_EDIT_REQUEST = "COUPON_EDIT_REQUEST";
export const COUPON_EDIT_SUCCESS = "COUPON_EDIT_SUCCESS";
export const COUPON_EDIT_FAIL = "COUPON_EDIT_FAIL";

export const COUPON_DELETE_REQUEST = "COUPON_DELETE_REQUEST";
export const COUPON_DELETE_SUCCESS = "COUPON_DELETE_SUCCESS";
export const COUPON_DELETE_FAIL = "COUPON_DELETE_FAIL";
export const COUPON_DELETE_RESET = "COUPON_DELETE_RESET";

export const COUPON_DETAILS_REQUEST = "COUPON_DETAILS_REQUEST";
export const COUPON_DETAILS_SUCCESS = "COUPON_DETAILS_SUCCESS";
export const COUPON_DETAILS_FAIL = "COUPON_DETAILS_FAIL";


export const COUPON_ADD_USER_REQUEST = "COUPON_ADD_USER_REQUEST";
export const COUPON_ADD_USER_SUCCESS = "COUPON_ADD_USER_SUCCESS";
export const COUPON_ADD_USER_FAIL = "COUPON_ADD_USER_FAIL";
export const COUPON_ADD_USER_RESET = "COUPON_ADD_USER_RESET";