export const POTS_LIST_REQUEST = "POTS_LIST_REQUEST";
export const POTS_LIST_SUCCESS = "POTS_LIST_SUCCESS";
export const POTS_LIST_FAIL = "POTS_LIST_FAIL";

export const POTS_DETAILS_REQUEST = "POTS_DETAILS_REQUEST";
export const POTS_DETAILS_SUCCESS = "POTS_DETAILS_SUCCESS";
export const POTS_DETAILS_FAIL = "POTS_DETAILS_FAIL";
export const POTS_DETAILS_RESET = "POTS_DETAILS_RESET";

export const POTS_DETAILSTYPE_REQUEST = "POTS_DETAILSTYPE_REQUEST";
export const POTS_DETAILSTYPE_SUCCESS = "POTS_DETAILSTYPE_SUCCESS";
export const POTS_DETAILSTYPE_FAIL = "POTS_DETAILSTYPE_FAIL";
export const POTS_DETAILSTYPE_RESET = "POTS_DETAILSTYPE_RESET";

export const POTS_FORLISTSCREEN_REQUEST = "POTS_FORLISTSCREEN_REQUEST";
export const POTS_FORLISTSCREEN_SUCCESS = "POTS_FORLISTSCREEN_SUCCESS";
export const POTS_FORLISTSCREEN_FAIL = "POTS_FORLISTSCREEN_FAIL";
export const POTS_FORLISTSCREEN_RESET = "POTS_FORLISTSCREEN_RESET";

export const POTS_DELETE_REQUEST = "POTS_DELETE_REQUEST";
export const POTS_DELETE_SUCCESS = "POTS_DELETE_SUCCESS";
export const POTS_DELETE_FAIL = "POTS_DELETE_FAIL";
export const POTS_DELETE_RESET = "POTS_DELETE_RESET";

export const POTS_CREATE_REQUEST = "POTS_CREATE_REQUEST";
export const POTS_CREATE_SUCCESS = "POTS_CREATE_SUCCESS";
export const POTS_CREATE_FAIL = "POTS_CREATE_FAIL";
export const POTS_CREATE_RESET = "POTS_CREATE_RESET";

export const POTS_UPDATE_REQUEST = "POTS_UPDATE_REQUEST";
export const POTS_UPDATE_SUCCESS = "POTS_UPDATE_SUCCESS";
export const POTS_UPDATE_FAIL = "POTS_UPDATE_FAIL";
export const POTS_UPDATE_RESET = "POTS_UPDATE_RESET";

export const POTS_CREATE_REVIEW_REQUEST = "POTS_CREATE_REVIEW_REQUEST";
export const POTS_CREATE_REVIEW_SUCCESS = "POTS_CREATE_REVIEW_SUCCESS";
export const POTS_CREATE_REVIEW_FAIL = "POTS_CREATE_REVIEW_FAIL";
export const POTS_CREATE_REVIEW_RESET = "POTS_CREATE_REVIEW_RESET";

export const POTS_TOP_REQUEST = "POTS_TOP_REQUEST";
export const POTS_TOP_SUCCESS = "POTS_TOP_SUCCESS";
export const POTS_TOP_FAIL = "POTS_TOP_FAIL";

export const GET_POTS_SUGGESTIONS = 'GET_POTS_SUGGESTIONS'
