

export const GET_REST_REQUEST = 'GET_REST_REQUEST'
export const GET_REST_SUCCESS = 'GET_REST_SUCCESS'
export const GET_REST_FAIL = 'GET_REST_FAIL'

export const GET_REST_DETAILS_REQUEST = 'GET_REST_DETAILS_REQUEST'
export const GET_REST_DETAILS_SUCCESS = 'GET_REST_DETAILS_SUCCESS'
export const GET_REST_DETAILS_FAIL = 'GET_REST_DETAILS_FAIL'

export const UPDATE_REST_DETAILS_REQUEST = 'UPDATE_REST_DETAILS_REQUEST'
export const UPDATE_REST_DETAILS_SUCCESS = 'UPDATE_REST_DETAILS_SUCCESS'
export const UPDATE_REST_DETAILS_FAIL = 'UPDATE_REST_DETAILS_FAIL'
export const UPDATE_REST_DETAILS_RESET = 'UPDATE_REST_DETAILS_RESET'

