export const WHOLESALE_ADD_REQUEST = "WHOLESALE_ADD_REQUEST"
export const WHOLESALE_ADD_SUCCESS = "WHOLESALE_ADD_SUCCESS"
export const WHOLESALE_ADD_FAIL = "WHOLESALE_ADD_FAIL"

export const WHOLESALE_GET_REQUEST = "WHOLESALE_GET_REQUEST"
export const WHOLESALE_GET_SUCCESS = "WHOLESALE_GET_SUCCESS"
export const WHOLESALE_GET_FAIL = "WHOLESALE_GET_FAIL"